// Code generated by mockery v2.52.3. DO NOT EDIT.

package mock

import (
	problem "gsprit/problem"

	mock "github.com/stretchr/testify/mock"
)

// MockDelivery is an autogenerated mock type for the Delivery type
type MockDelivery struct {
	mock.Mock
}

type MockDelivery_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDelivery) EXPECT() *MockDelivery_Expecter {
	return &MockDelivery_Expecter{mock: &_m.Mock}
}

// Activities provides a mock function with no fields
func (_m *MockDelivery) Activities() []problem.Activity {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Activities")
	}

	var r0 []problem.Activity
	if rf, ok := ret.Get(0).(func() []problem.Activity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]problem.Activity)
		}
	}

	return r0
}

// MockDelivery_Activities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activities'
type MockDelivery_Activities_Call struct {
	*mock.Call
}

// Activities is a helper method to define mock.On call
func (_e *MockDelivery_Expecter) Activities() *MockDelivery_Activities_Call {
	return &MockDelivery_Activities_Call{Call: _e.mock.On("Activities")}
}

func (_c *MockDelivery_Activities_Call) Run(run func()) *MockDelivery_Activities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDelivery_Activities_Call) Return(_a0 []problem.Activity) *MockDelivery_Activities_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDelivery_Activities_Call) RunAndReturn(run func() []problem.Activity) *MockDelivery_Activities_Call {
	_c.Call.Return(run)
	return _c
}

// Id provides a mock function with no fields
func (_m *MockDelivery) Id() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Id")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDelivery_Id_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Id'
type MockDelivery_Id_Call struct {
	*mock.Call
}

// Id is a helper method to define mock.On call
func (_e *MockDelivery_Expecter) Id() *MockDelivery_Id_Call {
	return &MockDelivery_Id_Call{Call: _e.mock.On("Id")}
}

func (_c *MockDelivery_Id_Call) Run(run func()) *MockDelivery_Id_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDelivery_Id_Call) Return(_a0 string) *MockDelivery_Id_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDelivery_Id_Call) RunAndReturn(run func() string) *MockDelivery_Id_Call {
	_c.Call.Return(run)
	return _c
}

// Index provides a mock function with no fields
func (_m *MockDelivery) Index() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockDelivery_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type MockDelivery_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
func (_e *MockDelivery_Expecter) Index() *MockDelivery_Index_Call {
	return &MockDelivery_Index_Call{Call: _e.mock.On("Index")}
}

func (_c *MockDelivery_Index_Call) Run(run func()) *MockDelivery_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDelivery_Index_Call) Return(_a0 int) *MockDelivery_Index_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDelivery_Index_Call) RunAndReturn(run func() int) *MockDelivery_Index_Call {
	_c.Call.Return(run)
	return _c
}

// JobType provides a mock function with no fields
func (_m *MockDelivery) JobType() problem.JobType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for JobType")
	}

	var r0 problem.JobType
	if rf, ok := ret.Get(0).(func() problem.JobType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(problem.JobType)
	}

	return r0
}

// MockDelivery_JobType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JobType'
type MockDelivery_JobType_Call struct {
	*mock.Call
}

// JobType is a helper method to define mock.On call
func (_e *MockDelivery_Expecter) JobType() *MockDelivery_JobType_Call {
	return &MockDelivery_JobType_Call{Call: _e.mock.On("JobType")}
}

func (_c *MockDelivery_JobType_Call) Run(run func()) *MockDelivery_JobType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDelivery_JobType_Call) Return(_a0 problem.JobType) *MockDelivery_JobType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDelivery_JobType_Call) RunAndReturn(run func() problem.JobType) *MockDelivery_JobType_Call {
	_c.Call.Return(run)
	return _c
}

// Location provides a mock function with no fields
func (_m *MockDelivery) Location() *problem.Location {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Location")
	}

	var r0 *problem.Location
	if rf, ok := ret.Get(0).(func() *problem.Location); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*problem.Location)
		}
	}

	return r0
}

// MockDelivery_Location_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Location'
type MockDelivery_Location_Call struct {
	*mock.Call
}

// Location is a helper method to define mock.On call
func (_e *MockDelivery_Expecter) Location() *MockDelivery_Location_Call {
	return &MockDelivery_Location_Call{Call: _e.mock.On("Location")}
}

func (_c *MockDelivery_Location_Call) Run(run func()) *MockDelivery_Location_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDelivery_Location_Call) Return(_a0 *problem.Location) *MockDelivery_Location_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDelivery_Location_Call) RunAndReturn(run func() *problem.Location) *MockDelivery_Location_Call {
	_c.Call.Return(run)
	return _c
}

// MaxTimeInVehicle provides a mock function with no fields
func (_m *MockDelivery) MaxTimeInVehicle() float64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MaxTimeInVehicle")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// MockDelivery_MaxTimeInVehicle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxTimeInVehicle'
type MockDelivery_MaxTimeInVehicle_Call struct {
	*mock.Call
}

// MaxTimeInVehicle is a helper method to define mock.On call
func (_e *MockDelivery_Expecter) MaxTimeInVehicle() *MockDelivery_MaxTimeInVehicle_Call {
	return &MockDelivery_MaxTimeInVehicle_Call{Call: _e.mock.On("MaxTimeInVehicle")}
}

func (_c *MockDelivery_MaxTimeInVehicle_Call) Run(run func()) *MockDelivery_MaxTimeInVehicle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDelivery_MaxTimeInVehicle_Call) Return(_a0 float64) *MockDelivery_MaxTimeInVehicle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDelivery_MaxTimeInVehicle_Call) RunAndReturn(run func() float64) *MockDelivery_MaxTimeInVehicle_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockDelivery) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDelivery_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockDelivery_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockDelivery_Expecter) Name() *MockDelivery_Name_Call {
	return &MockDelivery_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockDelivery_Name_Call) Run(run func()) *MockDelivery_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDelivery_Name_Call) Return(_a0 string) *MockDelivery_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDelivery_Name_Call) RunAndReturn(run func() string) *MockDelivery_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Priority provides a mock function with no fields
func (_m *MockDelivery) Priority() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Priority")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockDelivery_Priority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Priority'
type MockDelivery_Priority_Call struct {
	*mock.Call
}

// Priority is a helper method to define mock.On call
func (_e *MockDelivery_Expecter) Priority() *MockDelivery_Priority_Call {
	return &MockDelivery_Priority_Call{Call: _e.mock.On("Priority")}
}

func (_c *MockDelivery_Priority_Call) Run(run func()) *MockDelivery_Priority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDelivery_Priority_Call) Return(_a0 int) *MockDelivery_Priority_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDelivery_Priority_Call) RunAndReturn(run func() int) *MockDelivery_Priority_Call {
	_c.Call.Return(run)
	return _c
}

// RequiredSkills provides a mock function with no fields
func (_m *MockDelivery) RequiredSkills() *problem.Skills {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequiredSkills")
	}

	var r0 *problem.Skills
	if rf, ok := ret.Get(0).(func() *problem.Skills); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*problem.Skills)
		}
	}

	return r0
}

// MockDelivery_RequiredSkills_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequiredSkills'
type MockDelivery_RequiredSkills_Call struct {
	*mock.Call
}

// RequiredSkills is a helper method to define mock.On call
func (_e *MockDelivery_Expecter) RequiredSkills() *MockDelivery_RequiredSkills_Call {
	return &MockDelivery_RequiredSkills_Call{Call: _e.mock.On("RequiredSkills")}
}

func (_c *MockDelivery_RequiredSkills_Call) Run(run func()) *MockDelivery_RequiredSkills_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDelivery_RequiredSkills_Call) Return(_a0 *problem.Skills) *MockDelivery_RequiredSkills_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDelivery_RequiredSkills_Call) RunAndReturn(run func() *problem.Skills) *MockDelivery_RequiredSkills_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceDuration provides a mock function with no fields
func (_m *MockDelivery) ServiceDuration() float64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServiceDuration")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// MockDelivery_ServiceDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceDuration'
type MockDelivery_ServiceDuration_Call struct {
	*mock.Call
}

// ServiceDuration is a helper method to define mock.On call
func (_e *MockDelivery_Expecter) ServiceDuration() *MockDelivery_ServiceDuration_Call {
	return &MockDelivery_ServiceDuration_Call{Call: _e.mock.On("ServiceDuration")}
}

func (_c *MockDelivery_ServiceDuration_Call) Run(run func()) *MockDelivery_ServiceDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDelivery_ServiceDuration_Call) Return(_a0 float64) *MockDelivery_ServiceDuration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDelivery_ServiceDuration_Call) RunAndReturn(run func() float64) *MockDelivery_ServiceDuration_Call {
	_c.Call.Return(run)
	return _c
}

// SetIndex provides a mock function with given fields: index
func (_m *MockDelivery) SetIndex(index int) {
	_m.Called(index)
}

// MockDelivery_SetIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetIndex'
type MockDelivery_SetIndex_Call struct {
	*mock.Call
}

// SetIndex is a helper method to define mock.On call
//   - index int
func (_e *MockDelivery_Expecter) SetIndex(index interface{}) *MockDelivery_SetIndex_Call {
	return &MockDelivery_SetIndex_Call{Call: _e.mock.On("SetIndex", index)}
}

func (_c *MockDelivery_SetIndex_Call) Run(run func(index int)) *MockDelivery_SetIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockDelivery_SetIndex_Call) Return() *MockDelivery_SetIndex_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDelivery_SetIndex_Call) RunAndReturn(run func(int)) *MockDelivery_SetIndex_Call {
	_c.Run(run)
	return _c
}

// SetUserData provides a mock function with given fields: d
func (_m *MockDelivery) SetUserData(d interface{}) {
	_m.Called(d)
}

// MockDelivery_SetUserData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserData'
type MockDelivery_SetUserData_Call struct {
	*mock.Call
}

// SetUserData is a helper method to define mock.On call
//   - d interface{}
func (_e *MockDelivery_Expecter) SetUserData(d interface{}) *MockDelivery_SetUserData_Call {
	return &MockDelivery_SetUserData_Call{Call: _e.mock.On("SetUserData", d)}
}

func (_c *MockDelivery_SetUserData_Call) Run(run func(d interface{})) *MockDelivery_SetUserData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockDelivery_SetUserData_Call) Return() *MockDelivery_SetUserData_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDelivery_SetUserData_Call) RunAndReturn(run func(interface{})) *MockDelivery_SetUserData_Call {
	_c.Run(run)
	return _c
}

// Size provides a mock function with no fields
func (_m *MockDelivery) Size() *problem.Capacity {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 *problem.Capacity
	if rf, ok := ret.Get(0).(func() *problem.Capacity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*problem.Capacity)
		}
	}

	return r0
}

// MockDelivery_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockDelivery_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockDelivery_Expecter) Size() *MockDelivery_Size_Call {
	return &MockDelivery_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockDelivery_Size_Call) Run(run func()) *MockDelivery_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDelivery_Size_Call) Return(_a0 *problem.Capacity) *MockDelivery_Size_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDelivery_Size_Call) RunAndReturn(run func() *problem.Capacity) *MockDelivery_Size_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with no fields
func (_m *MockDelivery) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDelivery_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockDelivery_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockDelivery_Expecter) String() *MockDelivery_String_Call {
	return &MockDelivery_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockDelivery_String_Call) Run(run func()) *MockDelivery_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDelivery_String_Call) Return(_a0 string) *MockDelivery_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDelivery_String_Call) RunAndReturn(run func() string) *MockDelivery_String_Call {
	_c.Call.Return(run)
	return _c
}

// TimeWindow provides a mock function with no fields
func (_m *MockDelivery) TimeWindow() problem.TimeWindow {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TimeWindow")
	}

	var r0 problem.TimeWindow
	if rf, ok := ret.Get(0).(func() problem.TimeWindow); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(problem.TimeWindow)
		}
	}

	return r0
}

// MockDelivery_TimeWindow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TimeWindow'
type MockDelivery_TimeWindow_Call struct {
	*mock.Call
}

// TimeWindow is a helper method to define mock.On call
func (_e *MockDelivery_Expecter) TimeWindow() *MockDelivery_TimeWindow_Call {
	return &MockDelivery_TimeWindow_Call{Call: _e.mock.On("TimeWindow")}
}

func (_c *MockDelivery_TimeWindow_Call) Run(run func()) *MockDelivery_TimeWindow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDelivery_TimeWindow_Call) Return(_a0 problem.TimeWindow) *MockDelivery_TimeWindow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDelivery_TimeWindow_Call) RunAndReturn(run func() problem.TimeWindow) *MockDelivery_TimeWindow_Call {
	_c.Call.Return(run)
	return _c
}

// TimeWindows provides a mock function with no fields
func (_m *MockDelivery) TimeWindows() []problem.TimeWindow {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TimeWindows")
	}

	var r0 []problem.TimeWindow
	if rf, ok := ret.Get(0).(func() []problem.TimeWindow); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]problem.TimeWindow)
		}
	}

	return r0
}

// MockDelivery_TimeWindows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TimeWindows'
type MockDelivery_TimeWindows_Call struct {
	*mock.Call
}

// TimeWindows is a helper method to define mock.On call
func (_e *MockDelivery_Expecter) TimeWindows() *MockDelivery_TimeWindows_Call {
	return &MockDelivery_TimeWindows_Call{Call: _e.mock.On("TimeWindows")}
}

func (_c *MockDelivery_TimeWindows_Call) Run(run func()) *MockDelivery_TimeWindows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDelivery_TimeWindows_Call) Return(_a0 []problem.TimeWindow) *MockDelivery_TimeWindows_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDelivery_TimeWindows_Call) RunAndReturn(run func() []problem.TimeWindow) *MockDelivery_TimeWindows_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function with no fields
func (_m *MockDelivery) Type() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDelivery_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockDelivery_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockDelivery_Expecter) Type() *MockDelivery_Type_Call {
	return &MockDelivery_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockDelivery_Type_Call) Run(run func()) *MockDelivery_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDelivery_Type_Call) Return(_a0 string) *MockDelivery_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDelivery_Type_Call) RunAndReturn(run func() string) *MockDelivery_Type_Call {
	_c.Call.Return(run)
	return _c
}

// UserData provides a mock function with no fields
func (_m *MockDelivery) UserData() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserData")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockDelivery_UserData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserData'
type MockDelivery_UserData_Call struct {
	*mock.Call
}

// UserData is a helper method to define mock.On call
func (_e *MockDelivery_Expecter) UserData() *MockDelivery_UserData_Call {
	return &MockDelivery_UserData_Call{Call: _e.mock.On("UserData")}
}

func (_c *MockDelivery_UserData_Call) Run(run func()) *MockDelivery_UserData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDelivery_UserData_Call) Return(_a0 interface{}) *MockDelivery_UserData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDelivery_UserData_Call) RunAndReturn(run func() interface{}) *MockDelivery_UserData_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDelivery creates a new instance of MockDelivery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDelivery(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDelivery {
	mock := &MockDelivery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
