// Code generated by mockery v2.52.3. DO NOT EDIT.

package mock

import (
	problem "gsprit/problem"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Activities provides a mock function with no fields
func (_m *MockService) Activities() []problem.Activity {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Activities")
	}

	var r0 []problem.Activity
	if rf, ok := ret.Get(0).(func() []problem.Activity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]problem.Activity)
		}
	}

	return r0
}

// MockService_Activities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activities'
type MockService_Activities_Call struct {
	*mock.Call
}

// Activities is a helper method to define mock.On call
func (_e *MockService_Expecter) Activities() *MockService_Activities_Call {
	return &MockService_Activities_Call{Call: _e.mock.On("Activities")}
}

func (_c *MockService_Activities_Call) Run(run func()) *MockService_Activities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Activities_Call) Return(_a0 []problem.Activity) *MockService_Activities_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Activities_Call) RunAndReturn(run func() []problem.Activity) *MockService_Activities_Call {
	_c.Call.Return(run)
	return _c
}

// Id provides a mock function with no fields
func (_m *MockService) Id() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Id")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockService_Id_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Id'
type MockService_Id_Call struct {
	*mock.Call
}

// Id is a helper method to define mock.On call
func (_e *MockService_Expecter) Id() *MockService_Id_Call {
	return &MockService_Id_Call{Call: _e.mock.On("Id")}
}

func (_c *MockService_Id_Call) Run(run func()) *MockService_Id_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Id_Call) Return(_a0 string) *MockService_Id_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Id_Call) RunAndReturn(run func() string) *MockService_Id_Call {
	_c.Call.Return(run)
	return _c
}

// Index provides a mock function with no fields
func (_m *MockService) Index() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockService_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type MockService_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
func (_e *MockService_Expecter) Index() *MockService_Index_Call {
	return &MockService_Index_Call{Call: _e.mock.On("Index")}
}

func (_c *MockService_Index_Call) Run(run func()) *MockService_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Index_Call) Return(_a0 int) *MockService_Index_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Index_Call) RunAndReturn(run func() int) *MockService_Index_Call {
	_c.Call.Return(run)
	return _c
}

// JobType provides a mock function with no fields
func (_m *MockService) JobType() problem.JobType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for JobType")
	}

	var r0 problem.JobType
	if rf, ok := ret.Get(0).(func() problem.JobType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(problem.JobType)
	}

	return r0
}

// MockService_JobType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JobType'
type MockService_JobType_Call struct {
	*mock.Call
}

// JobType is a helper method to define mock.On call
func (_e *MockService_Expecter) JobType() *MockService_JobType_Call {
	return &MockService_JobType_Call{Call: _e.mock.On("JobType")}
}

func (_c *MockService_JobType_Call) Run(run func()) *MockService_JobType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_JobType_Call) Return(_a0 problem.JobType) *MockService_JobType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_JobType_Call) RunAndReturn(run func() problem.JobType) *MockService_JobType_Call {
	_c.Call.Return(run)
	return _c
}

// Location provides a mock function with no fields
func (_m *MockService) Location() *problem.Location {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Location")
	}

	var r0 *problem.Location
	if rf, ok := ret.Get(0).(func() *problem.Location); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*problem.Location)
		}
	}

	return r0
}

// MockService_Location_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Location'
type MockService_Location_Call struct {
	*mock.Call
}

// Location is a helper method to define mock.On call
func (_e *MockService_Expecter) Location() *MockService_Location_Call {
	return &MockService_Location_Call{Call: _e.mock.On("Location")}
}

func (_c *MockService_Location_Call) Run(run func()) *MockService_Location_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Location_Call) Return(_a0 *problem.Location) *MockService_Location_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Location_Call) RunAndReturn(run func() *problem.Location) *MockService_Location_Call {
	_c.Call.Return(run)
	return _c
}

// MaxTimeInVehicle provides a mock function with no fields
func (_m *MockService) MaxTimeInVehicle() float64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MaxTimeInVehicle")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// MockService_MaxTimeInVehicle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxTimeInVehicle'
type MockService_MaxTimeInVehicle_Call struct {
	*mock.Call
}

// MaxTimeInVehicle is a helper method to define mock.On call
func (_e *MockService_Expecter) MaxTimeInVehicle() *MockService_MaxTimeInVehicle_Call {
	return &MockService_MaxTimeInVehicle_Call{Call: _e.mock.On("MaxTimeInVehicle")}
}

func (_c *MockService_MaxTimeInVehicle_Call) Run(run func()) *MockService_MaxTimeInVehicle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_MaxTimeInVehicle_Call) Return(_a0 float64) *MockService_MaxTimeInVehicle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_MaxTimeInVehicle_Call) RunAndReturn(run func() float64) *MockService_MaxTimeInVehicle_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockService) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockService_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockService_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockService_Expecter) Name() *MockService_Name_Call {
	return &MockService_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockService_Name_Call) Run(run func()) *MockService_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Name_Call) Return(_a0 string) *MockService_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Name_Call) RunAndReturn(run func() string) *MockService_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Priority provides a mock function with no fields
func (_m *MockService) Priority() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Priority")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockService_Priority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Priority'
type MockService_Priority_Call struct {
	*mock.Call
}

// Priority is a helper method to define mock.On call
func (_e *MockService_Expecter) Priority() *MockService_Priority_Call {
	return &MockService_Priority_Call{Call: _e.mock.On("Priority")}
}

func (_c *MockService_Priority_Call) Run(run func()) *MockService_Priority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Priority_Call) Return(_a0 int) *MockService_Priority_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Priority_Call) RunAndReturn(run func() int) *MockService_Priority_Call {
	_c.Call.Return(run)
	return _c
}

// RequiredSkills provides a mock function with no fields
func (_m *MockService) RequiredSkills() *problem.Skills {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequiredSkills")
	}

	var r0 *problem.Skills
	if rf, ok := ret.Get(0).(func() *problem.Skills); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*problem.Skills)
		}
	}

	return r0
}

// MockService_RequiredSkills_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequiredSkills'
type MockService_RequiredSkills_Call struct {
	*mock.Call
}

// RequiredSkills is a helper method to define mock.On call
func (_e *MockService_Expecter) RequiredSkills() *MockService_RequiredSkills_Call {
	return &MockService_RequiredSkills_Call{Call: _e.mock.On("RequiredSkills")}
}

func (_c *MockService_RequiredSkills_Call) Run(run func()) *MockService_RequiredSkills_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_RequiredSkills_Call) Return(_a0 *problem.Skills) *MockService_RequiredSkills_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_RequiredSkills_Call) RunAndReturn(run func() *problem.Skills) *MockService_RequiredSkills_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceDuration provides a mock function with no fields
func (_m *MockService) ServiceDuration() float64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServiceDuration")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// MockService_ServiceDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceDuration'
type MockService_ServiceDuration_Call struct {
	*mock.Call
}

// ServiceDuration is a helper method to define mock.On call
func (_e *MockService_Expecter) ServiceDuration() *MockService_ServiceDuration_Call {
	return &MockService_ServiceDuration_Call{Call: _e.mock.On("ServiceDuration")}
}

func (_c *MockService_ServiceDuration_Call) Run(run func()) *MockService_ServiceDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_ServiceDuration_Call) Return(_a0 float64) *MockService_ServiceDuration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_ServiceDuration_Call) RunAndReturn(run func() float64) *MockService_ServiceDuration_Call {
	_c.Call.Return(run)
	return _c
}

// SetIndex provides a mock function with given fields: index
func (_m *MockService) SetIndex(index int) {
	_m.Called(index)
}

// MockService_SetIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetIndex'
type MockService_SetIndex_Call struct {
	*mock.Call
}

// SetIndex is a helper method to define mock.On call
//   - index int
func (_e *MockService_Expecter) SetIndex(index interface{}) *MockService_SetIndex_Call {
	return &MockService_SetIndex_Call{Call: _e.mock.On("SetIndex", index)}
}

func (_c *MockService_SetIndex_Call) Run(run func(index int)) *MockService_SetIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockService_SetIndex_Call) Return() *MockService_SetIndex_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_SetIndex_Call) RunAndReturn(run func(int)) *MockService_SetIndex_Call {
	_c.Run(run)
	return _c
}

// SetUserData provides a mock function with given fields: d
func (_m *MockService) SetUserData(d interface{}) {
	_m.Called(d)
}

// MockService_SetUserData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserData'
type MockService_SetUserData_Call struct {
	*mock.Call
}

// SetUserData is a helper method to define mock.On call
//   - d interface{}
func (_e *MockService_Expecter) SetUserData(d interface{}) *MockService_SetUserData_Call {
	return &MockService_SetUserData_Call{Call: _e.mock.On("SetUserData", d)}
}

func (_c *MockService_SetUserData_Call) Run(run func(d interface{})) *MockService_SetUserData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockService_SetUserData_Call) Return() *MockService_SetUserData_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_SetUserData_Call) RunAndReturn(run func(interface{})) *MockService_SetUserData_Call {
	_c.Run(run)
	return _c
}

// Size provides a mock function with no fields
func (_m *MockService) Size() *problem.Capacity {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 *problem.Capacity
	if rf, ok := ret.Get(0).(func() *problem.Capacity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*problem.Capacity)
		}
	}

	return r0
}

// MockService_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockService_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockService_Expecter) Size() *MockService_Size_Call {
	return &MockService_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockService_Size_Call) Run(run func()) *MockService_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Size_Call) Return(_a0 *problem.Capacity) *MockService_Size_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Size_Call) RunAndReturn(run func() *problem.Capacity) *MockService_Size_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with no fields
func (_m *MockService) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockService_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockService_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockService_Expecter) String() *MockService_String_Call {
	return &MockService_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockService_String_Call) Run(run func()) *MockService_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_String_Call) Return(_a0 string) *MockService_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_String_Call) RunAndReturn(run func() string) *MockService_String_Call {
	_c.Call.Return(run)
	return _c
}

// TimeWindow provides a mock function with no fields
func (_m *MockService) TimeWindow() problem.TimeWindow {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TimeWindow")
	}

	var r0 problem.TimeWindow
	if rf, ok := ret.Get(0).(func() problem.TimeWindow); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(problem.TimeWindow)
		}
	}

	return r0
}

// MockService_TimeWindow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TimeWindow'
type MockService_TimeWindow_Call struct {
	*mock.Call
}

// TimeWindow is a helper method to define mock.On call
func (_e *MockService_Expecter) TimeWindow() *MockService_TimeWindow_Call {
	return &MockService_TimeWindow_Call{Call: _e.mock.On("TimeWindow")}
}

func (_c *MockService_TimeWindow_Call) Run(run func()) *MockService_TimeWindow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_TimeWindow_Call) Return(_a0 problem.TimeWindow) *MockService_TimeWindow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_TimeWindow_Call) RunAndReturn(run func() problem.TimeWindow) *MockService_TimeWindow_Call {
	_c.Call.Return(run)
	return _c
}

// TimeWindows provides a mock function with no fields
func (_m *MockService) TimeWindows() []problem.TimeWindow {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TimeWindows")
	}

	var r0 []problem.TimeWindow
	if rf, ok := ret.Get(0).(func() []problem.TimeWindow); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]problem.TimeWindow)
		}
	}

	return r0
}

// MockService_TimeWindows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TimeWindows'
type MockService_TimeWindows_Call struct {
	*mock.Call
}

// TimeWindows is a helper method to define mock.On call
func (_e *MockService_Expecter) TimeWindows() *MockService_TimeWindows_Call {
	return &MockService_TimeWindows_Call{Call: _e.mock.On("TimeWindows")}
}

func (_c *MockService_TimeWindows_Call) Run(run func()) *MockService_TimeWindows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_TimeWindows_Call) Return(_a0 []problem.TimeWindow) *MockService_TimeWindows_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_TimeWindows_Call) RunAndReturn(run func() []problem.TimeWindow) *MockService_TimeWindows_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function with no fields
func (_m *MockService) Type() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockService_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockService_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockService_Expecter) Type() *MockService_Type_Call {
	return &MockService_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockService_Type_Call) Run(run func()) *MockService_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Type_Call) Return(_a0 string) *MockService_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Type_Call) RunAndReturn(run func() string) *MockService_Type_Call {
	_c.Call.Return(run)
	return _c
}

// UserData provides a mock function with no fields
func (_m *MockService) UserData() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserData")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockService_UserData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserData'
type MockService_UserData_Call struct {
	*mock.Call
}

// UserData is a helper method to define mock.On call
func (_e *MockService_Expecter) UserData() *MockService_UserData_Call {
	return &MockService_UserData_Call{Call: _e.mock.On("UserData")}
}

func (_c *MockService_UserData_Call) Run(run func()) *MockService_UserData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_UserData_Call) Return(_a0 interface{}) *MockService_UserData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_UserData_Call) RunAndReturn(run func() interface{}) *MockService_UserData_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
